const songsTypes = {
    FETCH_SONGS_START: 'FETCH_SONGS_START',
    FETCH_SONGS_SUCCESS: 'FETCH_SONGS_SUCCESS',
    FETCH_SONGS_ERROR: 'FETCH_SONGS_ERROR',

    FETCH_PLAYLIST_SONGS_START: 'FETCH_PLAYLIST_SONGS_START',
    FETCH_PLAYLIST_SONGS_ERROR: 'FETCH_PLAYLIST_SONGS_START',
    FETCH_PLAYLIST_SONGS_SUCCESS: 'FETCH_PLAYLIST_SONGS_SUCCESS',

    SET_CURRENT_SONG: 'SET_CURRENT_SONG',

    PLAY_SONG: 'PLAY_SONG',
    STOP_SONG: 'STOP_SONG',
    PAUSE_SONG: 'PAUSE_SONG',
    RESUME_SONG: 'RESUME_SONG',
    INCREASE_SONG_TIME: 'INCREASE_SONG_TIME',
}

export default songsTypes