const artistTypes = {
    FETCH_ARTISTS_START: 'FETCH_ARTISTS_START',
    FETCH_ARTISTS_SUCCESS: 'FETCH_ARTISTS_SUCCESS',
    FETCH_ARTISTS_ERROR: 'FETCH_ARTISTS_ERROR',

    FETCH_ARTIST_SONGS_START: 'FETCH_ARTIST_SONGS_START',
    FETCH_ARTIST_SONGS_SUCCESS: 'FETCH_ARTIST_SONGS_SUCCESS',
    FETCH_ARTIST_SONGS_ERROR: 'FETCH_ARTIST_SONGS_ERROR',

    SET_ARTIST_IDS: 'SET_ARTIST_IDS'
}

export default artistTypes