const playlistTypes = {
    FETCH_PLAYLIST_MENU_START: 'FETCH_PLAYLIST_MENU_START',
    FETCH_PLAYLIST_MENU_SUCCESS: 'FETCH_PLAYLIST_MENU_SUCCESS',
    FETCH_PLAYLIST_MENU_ERROR: 'FETCH_PLAYLIST_MENU_ERROR',

    FETCH_USER_PLAYLISTS_START: 'FETCH_USER_PLAYLISTS_START',
    FETCH_USER_PLAYLISTS_SUCCESS: 'FETCH_USER_PLAYLISTS_SUCCESS',
    FETCH_USER_PLAYLISTS_ERROR: 'FETCH_USER_PLAYLISTS_ERROR',

    FETCH_FEATURED_PLAYLISTS_START: 'FETCH_FEATURED_PLAYLISTS_START',
    FETCH_FEATURED_PLAYLISTS_SUCCESS: 'FETCH_FEATURED_PLAYLISTS_SUCCESS',
    FETCH_FEATURED_PLAYLISTS_ERROR: 'FETCH_FEATURED_PLAYLISTS_ERROR',

    ADD_PLAYLIST_ITEM: 'ADD_PLAYLIST_ITEM'
}

export default playlistTypes