const playlistTypes = {
    FETCH_USER_PLAYLISTS_START: 'FETCH_USER_PLAYLISTS_START',
    FETCH_USER_PLAYLISTS_SUCCESS: 'FETCH_USER_PLAYLISTS_SUCCESS',
    FETCH_USER_PLAYLISTS_ERROR: 'FETCH_USER_PLAYLISTS_ERROR',

    FETCH_FEATURED_PLAYLISTS_START: 'FETCH_FEATURED_PLAYLISTS_START',
    FETCH_FEATURED_PLAYLISTS_SUCCESS: 'FETCH_FEATURED_PLAYLISTS_SUCCESS',
    FETCH_FEATURED_PLAYLISTS_ERROR: 'FETCH_FEATURED_PLAYLISTS_ERROR',

    SEARCH_PLAYLISTS_START: 'SEARCH_PLAYLISTS_START',
    SEARCH_PLAYLISTS_ERROR: 'SEARCH_PLAYLISTS_ERROR',
    SEARCH_PLAYLISTS_SUCCESS: 'SEARCH_PLAYLISTS_SUCCESS',

    FETCH_CATEGORY_PLAYLISTS_START: 'FETCH_CATEGORY_PLAYLISTS_START',
    FETCH_CATEGORY_PLAYLISTS_ERROR: 'FETCH_CATEGORY_PLAYLISTS_ERROR',
    FETCH_CATEGORY_PLAYLISTS_SUCCESS: 'FETCH_CATEGORY_PLAYLISTS_SUCCESS',
}

export default playlistTypes