const userTypes = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',

    ADD_SONG_TO_LIBRARY_START: 'ADD_SONG_TO_LIBRARY_START',
    ADD_SONG_TO_LIBRARY_SUCCESS: 'ADD_SONG_TO_LIBRARY_SUCCESS',
    ADD_SONG_TO_LIBRARY_ERROR: 'ADD_SONG_TO_LIBRARY_ERROR',
}

export default userTypes