const browseTypes = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',

    FETCH_NEW_RELEASES_START: 'FETCH_NEW_RELEASES_START',
    FETCH_NEW_RELEASES_SUCCESS: 'FETCH_NEW_RELEASES_SUCCESS',
    FETCH_NEW_RELEASES_ERROR: 'FETCH_NEW_RELEASES_ERROR',

    FETCH_FEATURED_START: 'FETCH_FEATURED_START',
    FETCH_FEATURED_SUCCESS: 'FETCH_FEATURED_SUCCESS',
    FETCH_FEATURED_ERROR: 'FETCH_FEATURED_ERROR'
}

export default browseTypes